### ISSUE TITLE
shadowsocks-1.20151028 failed during the building phase. The exception was: ExitFailure 1

### ISSUE THREAD

**Issue by pxc3113** [rnons/shadowsocks-haskell#2]
zhiwei@zhiwei-Lenovo-Rescuer-15ISK:~$ cabal install shadowsocks
Warning: The package list for 'hackage.haskell.org' is 30 days old.
Run 'cabal update' to get the latest list of available packages.
Resolving dependencies...
Configuring shadowsocks-1.20151028...
Building shadowsocks-1.20151028...
Failed to install shadowsocks-1.20151028
Build log ( /home/zhiwei/.cabal/logs/shadowsocks-1.20151028.log ):
cabal: Entering directory '/tmp/cabal-tmp-29778/shadowsocks-1.20151028'
Configuring shadowsocks-1.20151028...
Building shadowsocks-1.20151028...
Preprocessing executable 'sslocal' for shadowsocks-1.20151028...
[1 of 3] Compiling Shadowsocks.Util ( Shadowsocks/Util.hs, dist/build/sslocal/sslocal-tmp/Shadowsocks/Util.o )

Shadowsocks/Util.hs:59:44: error:
    • Variable not in scope: (<>) :: Mod f3 a3 -> Mod f2 a2 -> t9
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)

Shadowsocks/Util.hs:59:57: error:
    • Variable not in scope: (<>) :: t9 -> Mod f1 a1 -> t8
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)

Shadowsocks/Util.hs:60:15: error:
    • Variable not in scope:
        (<>) :: t8 -> Mod f0 a0 -> Mod OptionFields String
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)

Shadowsocks/Util.hs:61:51: error:
    • Variable not in scope: (<>) :: Mod f7 a7 -> Mod f6 a6 -> t11
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)

Shadowsocks/Util.hs:61:64: error:
    • Variable not in scope: (<>) :: t11 -> Mod f5 a5 -> t10
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)

Shadowsocks/Util.hs:62:17: error:
    • Variable not in scope:
        (<>) :: t10 -> Mod f4 a4 -> Mod OptionFields Int
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)

Shadowsocks/Util.hs:63:50: error:
    • Variable not in scope: (<>) :: Mod f11 a11 -> Mod f10 a10 -> t13
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)

Shadowsocks/Util.hs:63:63: error:
    • Variable not in scope: (<>) :: t13 -> Mod f9 a9 -> t12
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)

Shadowsocks/Util.hs:64:17: error:
    • Variable not in scope:
        (<>) :: t12 -> Mod f8 a8 -> Mod OptionFields Int
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)

Shadowsocks/Util.hs:65:46: error:
    • Variable not in scope: (<>) :: Mod f15 a15 -> Mod f14 a14 -> t15
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)

Shadowsocks/Util.hs:65:59: error:
    • Variable not in scope: (<>) :: t15 -> Mod f13 a13 -> t14
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)

Shadowsocks/Util.hs:66:15: error:
    • Variable not in scope:
        (<>) :: t14 -> Mod f12 a12 -> Mod OptionFields String
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)

Shadowsocks/Util.hs:67:44: error:
    • Variable not in scope: (<>) :: Mod f19 a19 -> Mod f18 a18 -> t17
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)

Shadowsocks/Util.hs:67:57: error:
    • Variable not in scope: (<>) :: t17 -> Mod f17 a17 -> t16
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)

Shadowsocks/Util.hs:68:15: error:
    • Variable not in scope:
        (<>) :: t16 -> Mod f16 a16 -> Mod OptionFields String
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)

Shadowsocks/Util.hs:69:44: error:
    • Variable not in scope: (<>) :: Mod f23 a23 -> Mod f22 a22 -> t19
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)

Shadowsocks/Util.hs:69:57: error:
    • Variable not in scope: (<>) :: t19 -> Mod f21 a21 -> t18
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)

Shadowsocks/Util.hs:70:16: error:
    • Variable not in scope:
        (<>) :: t18 -> Mod f20 a20 -> Mod OptionFields String
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)

Shadowsocks/Util.hs:75:33: error:
    • Variable not in scope:
        (<>) :: InfoMod a25 -> InfoMod a24 -> InfoMod Options
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)

Shadowsocks/Util.hs:112:47: error:
    • Variable not in scope:
        (<>) :: t0 -> String -> (ByteString, ByteString, ByteString)
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)

Shadowsocks/Util.hs:120:12: error:
    • Variable not in scope: (<>) :: [Char] -> ByteString -> t1
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)

Shadowsocks/Util.hs:121:12: error:
    • Variable not in scope: (<>) :: t1 -> ByteString -> ByteString
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)

Shadowsocks/Util.hs:125:12: error:
    • Variable not in scope: (<>) :: [Char] -> ByteString -> t2
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)

Shadowsocks/Util.hs:126:16: error:
    • Variable not in scope: (<>) :: L.ByteString -> L.ByteString -> t4
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)

Shadowsocks/Util.hs:127:16: error:
    • Variable not in scope: (<>) :: t4 -> L.ByteString -> t3
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)

Shadowsocks/Util.hs:128:16: error:
    • Variable not in scope: (<>) :: t3 -> L.ByteString -> L.ByteString
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)

Shadowsocks/Util.hs:129:12: error:
    • Variable not in scope: (<>) :: t2 -> ByteString -> ByteString
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)

Shadowsocks/Util.hs:133:12: error:
    • Variable not in scope: (<>) :: [Char] -> ByteString -> t6
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)

Shadowsocks/Util.hs:133:49: error:
    • Variable not in scope: (<>) :: t6 -> ByteString -> t5
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)

Shadowsocks/Util.hs:133:57: error:
    • Variable not in scope: (<>) :: t5 -> ByteString -> ByteString
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)

Shadowsocks/Util.hs:141:47: error:
    • Variable not in scope: (<>) :: t7 -> String -> ByteString
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘<*>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative)
cabal: Leaving directory '/tmp/cabal-tmp-29778/shadowsocks-1.20151028'
cabal: Error: some packages failed to install:
shadowsocks-1.20151028 failed during the building phase. The exception was:
ExitFailure 1

**Comment by rnons** [comment]
Can you please try 

```
git clone https://github.com/rnons/shadowsocks-haskell
cd shadowsocks-haskell
stack install
```

The hackage version was released on 2015

**Comment by rnons** [comment]
I have just published version-1.20180408, please run

```
cabal update
cabal install shadowsocks
```
to get the new version. Let me know if you find any problems, thanks.

**Comment by luckypoem** [comment]
hi.

yudeMacBook-Air:shadowsocks-haskell brite$ ls
CHANGELOG.md		app			src
LICENSE			benchmark		stack.yaml
README.md		config.json		test.hs
Setup.hs		shadowsocks.cabal
yudeMacBook-Air:shadowsocks-haskell brite$ stack install
Downloaded lts-11.3 build plan.    
AesonException "Error in $.packages.cassava.constraints.flags: failed to parse field packages: failed to parse field constraints: failed to parse field flags: Invalid flag name: \"bytestring--lt-0_10_4\""
yudeMacBook-Air:shadowsocks-haskell brite$

how to fix it?

**Comment by rnons** [comment]
@luckypoem hi, I seems to have seen this error message before. Can you please check your `stack` version, mine is 

```
$ stack --version
Version 1.6.5
```

**Comment by luckypoem** [comment]
stack --version

Version 1.2.0, Git revision 241cd07d576d9c0c0e712e83d947e3dd64541c42 (4054 commits) x86_64 hpack-0.14.0.

my stack version is too old?

**Comment by rnons** [comment]
Yes, it should work after you upgrade to the latest version.

luckypoem <notifications@github.com> 於 2018年4月15日 週日 下午6:54 寫道：

**Comment by luckypoem** [comment]
yes,
i do it like this:
mv /usr/local/bin/stack /usr/local/bin/stack-1.2.0
curl -sSL https://get.haskellstack.org/ | sh (此步骤安装stack,版本为1.6.5）
brew install openssl

git clone https://github.com/rnons/shadowsocks-haskell
cd shadowsocks-haskell
stack install --extra-include-dirs=/usr/local/opt/openssl/include --extra-lib-dirs=/usr/local/opt/openssl/lib

最后显示：
...
Installing executable ssserver in /Users/brite/shadowsocks-haskell/.stack-work/install/x86_64-osx/lts-11.3/8.2.2/bin
Installing executable sslocal in /Users/brite/shadowsocks-haskell/.stack-work/install/x86_64-osx/lts-11.3/8.2.2/bin
Registering library for shadowsocks-1.20180408..
Completed 2 action(s).
Copying from /Users/brite/shadowsocks-haskell/.stack-work/install/x86_64-osx/lts-11.3/8.2.2/bin/sslocal to /Users/brite/.local/bin/sslocal
Copying from /Users/brite/shadowsocks-haskell/.stack-work/install/x86_64-osx/lts-11.3/8.2.2/bin/ssserver to /Users/brite/.local/bin/ssserver

Copied executables to /Users/brite/.local/bin:
- sslocal
- ssserver

**Comment by rnons** [comment]
`~/.local/bin` is where stack install binary into. You can either add it to your `$PATH` or manually run `~/.local/bin/sslocal`

**Comment by luckypoem** [comment]
@rnons 
我在mac上成功编译了shadowsocks-haskell，但在linux vps上却未能成功，可能是因为linux vps太烂了，是openvz的，所以可否请求你上传linux vps（64位）版的ssserver 到
https://github.com/rnons/shadowsocks-haskell/releases 这里？
非常感谢！

**Comment by rnons** [comment]
@luckypoem I'm not sure binary built on my computer can be used on your vps directly. Please read this article if you're interested: https://www.fpcomplete.com/blog/2016/10/static-compilation-with-stack

One approach is to build it in a docker image, which has the same linux version as your vps (I think openvz is not related here, ghc takes lots of memory when building) , then upload to your vps.

Since this is not related to the current issue, please file a new issue if you have other questions. Happy to help, thanks.
