### ISSUE TITLE
shadowsocksR support

### ISSUE THREAD

**Issue by hughjfchen** [rnons/shadowsocks-haskell#5]
Would you consider to add the shadowsocksR support?

**Comment by rnons** [comment]
Thanks for your interest in this project. I will consider if you can tell me the differences between shadowsocks and shadowsocksR. PR welcome as well.

**Comment by hughjfchen** [comment]
According to the wiki:
https://en.wikipedia.org/wiki/Shadowsocks
ShadowsocksR is a fork of Shadowsocks but stop development. So please ignore it. I will stick to SS instead of SSR.
